# h2 db connection properties
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/LoanDB
  username: root
  password: root
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
     
server:
  tomcat:
    basedir: my-tomcat
    accesslog:
      enabled: true
feign:
  hystrix:
    enabled: true
#ribbon:
#  eureka:
#    enabled: true